### ISSUE TITLE
Android: AndroidRuntime Error when Running an ID Capture Session

### ISSUE THREAD

**Issue by sanidkpc** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#11]
Hi @jakubdolejs, 
Thanks for continued solving the bug.
From the latest release I can successfully load Ver-ID and initialize the verid in our app `[android platform`]. 

```
var apiSecret = "..."; // Alternative way to set your Ver-ID API secret

verid.load(apiSecret).then(function() {
    // Ver-ID loaded successfully
    // You can now run registration, authentication or liveness detection
}).catch(function(error) {
    // Ver-ID failed to load
});
```
Ver-ID loaded successfully 👍 
now facing `AndroidRuntime Error when Running an ID Capture Session`
code snippet below. Accordingly to the documentation

```javascript
    var apiSecret = "api secret"; // Alternative way to set your Ver-ID API secret
    // Specify the front of the card as ISO ID-1 page with a face photo feature
    var front = new veridcredentials.Page(veridcredentials.ISOFormat.id1, new veridcredentials.FacePhotoFeature());
    // Specify the back of the card as ISO ID-1 page with a barcode feature
    var back = new veridcredentials.Page(veridcredentials.ISOFormat.id1, new veridcredentials.BarcodeFeature());
    // Specify the ID document
    var document = new veridcredentials.IDDocument([front, back]);
    // Create settings
    var settings = new veridcredentials.IDCaptureSessionSettings(document);
    // To detect a face you will be using for face recognition:
    settings.detectFaceForRecognition = true;
    // To show a session guide to the user:
    settings.showGuide = true;
    // To show the result of the session to the user:
    settings.showResult = true;

    verid.load(apiSecret).then(function() {
      console.log('Ver-ID loaded successfully');
      return veridcredentials.captureId(settings);
    }).then(function(response) {
      // See example response below
      console.log('response===',response)
    }).catch(function(error) {
      // ID capture session failed
      console.log('ID capture session failed===',error)
    });
```
 getting android run time error:
Error log from Logcat:
```
AndroidRuntime: FATAL EXCEPTION: main
    Process: net.demo.test.demodapp, PID: 30642
    java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/net.demo.test.demoapp-1/base.apk)
        at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
        at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:208)
        at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:110)
        at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:67)
        at android.support.v7.widget.Toolbar.setTitle(Toolbar.java:753)
        at android.support.v7.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:261)
        at android.support.v7.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:243)
        at android.support.v7.widget.ActionBarOverlayLayout.setWindowTitle(ActionBarOverlayLayout.java:621)
        at android.support.v7.app.AppCompatDelegateImplV9.onTitleChanged(AppCompatDelegateImplV9.java:631)
        at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.appliedrec.ver_ididcapture.GuideActivity.onCreate(GuideActivity.java:18)
        at android.app.Activity.performCreate(Activity.java:6666)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```
================================

Cordova project: ionic framework
ionic info:

```
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0, browser 5.0.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

Environment:

   ANDROID_HOME : /Users/bs228/Library/Android/sdk
```
I would greatly appreciate your help on this.
Thank you

**Comment by jakubdolejs** [comment]
I believe this is fixed in a9d8a54757ff1a5d016a48d4d5a6f7b4bd050f6c. Please reopen the ticket if you still get the error.
