### ISSUE TITLE
Android: Ver-ID-Credentials v4[ Branch swift4.2]: java.lang.Exception: VerID not found

### ISSUE THREAD

**Issue by sanitul** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#33]
Hi @jakubdolejs,
we are facing runtime error/ crash on Android, after front of the card scan. The app crash and reopen.
Android error logcat:
```
W/System.err: java.lang.Exception: VerID not found (id: 2)
08-05 19:07:46.907 8157-8157/? W/System.err:     at com.appliedrec.verid.core.VerID.getInstance(VerID.java:108)
        at com.appliedrec.ver_ididcapture.IDCaptureActivity.onCreate(IDCaptureActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:7074)
08-05 19:07:46.908 8157-8157/? W/System.err:     at android.app.Activity.performCreate(Activity.java:7065)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2796)
08-05 19:07:46.909 8157-8157/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2921)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
        at android.os.Handler.dispatchMessage(Handler.java:106)
08-05 19:07:46.910 8157-8157/? W/System.err:     at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6662)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
08-05 19:07:47.009 8157-8157/com.qa.app I/zygote: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
08-05 19:07:47.010 8157-8157/com.qa.app I/zygote:     at void android.support.v4.view.ViewCompat.setBackground(android.view.View, android.graphics.drawable.Drawable) (ViewCompat.java:2341)
```
**Cordova info:**
```
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.4-201903121725
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

Environment:

   ANDROID_HOME : /Users/bs228/Library/Android/sdk
```

**Comment by jakubdolejs** [comment]
Hi @sanitul, would you be able to send me the part of your Javascript code that calls the Ver-ID APIs? It looks like the instance of Ver-ID that was initially created is no longer available at the time of the face detection call. I'll see if I can find anything in the meantime. Thank you.

**Comment by sanitul** [comment]
Hi @jakubdolejs,
Here is the ver-id credentials code snippets we are using to load ID capturing processing.
```js
//we need to declare verid and veridcredentials, so that ionic project recognize plugin global variable.
declare var verid;
declare var veridcredentials;

let apiSecret = ENV.appliedRecognitionApiSecret;
let idFace;
let veridInstance;
let documentResponse: any = null;
veridcredentials.load(apiSecret).then((credentials) => {
	let front = new veridcredentials.Page(veridcredentials.ISOCardFormat.id1, new veridcredentials.FacePhotoFeature());
	let back = new veridcredentials.Page(veridcredentials.ISOCardFormat.id1, new veridcredentials.BarcodeFeature());
	let document = new veridcredentials.IDDocument([front, back]);
	let settings = new veridcredentials.IDCaptureSessionSettings(document);
	settings.detectFaceForRecognition = true;
	settings.showGuide = true;
	settings.showResult = false;
	settings.pageScanExpiryTime = 30;
	return credentials.captureId(settings);
}).then(idCaptureResult => {
	documentResponse = idCaptureResult;
	if (idCaptureResult.status == veridcredentials.IDCaptureStatus.SUCCESS) {
		idFace = idCaptureResult.document.pages[0].faces[0].face;
		return verid.load(apiSecret);
	}
}).then(instance => {
	if (instance) {
		veridInstance = instance;
		return veridInstance.captureLiveFace(new verid.LivenessDetectionSessionSettings());
	}
}).then(result => {
	if (result && !result.error) {
		var faces = result.attachments.map(attachment => {
			return attachment.face;
		});
		return veridInstance.compareFaces(idFace, faces[0]);
	}
}).then(comparisonResult => {
	if (comparisonResult) {
		let parsedDocument = documentResponse.document.pages[1].barcodes[0].parsed.document_t;
		let score = comparisonResult.score;
		this.appliedRecognitionVerificationSuccess(parsedDocument, score);
		if (comparisonResult.score >= comparisonResult.authenticationThreshold) {
			// The user is authenticated against the ID card
		}
	}
}).catch(error => {
	console.log('AR error====', error);
});
```

**Comment by jakubdolejs** [comment]
Hi @sanitul, I copied and pasted your code into a test and and I can't seem to be able to replicate the error after multiple tries. Is it intermittent or does it happen consistently?

**Comment by sanitul** [comment]
Hi @jakubdolejs ,
I always getting runtime error when the front of the card captured.
I run https://github.com/AppliedRecognition/Ver-ID-Credentials-Android-Sample
This project also showing the same error. Maybe the problem happens when verid process the getFace from ID card front, face detection.

Here is the Android runtime error from 'Ver-ID-Credentials-Android-Sample' project:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appliedrec.idcapturesample, PID: 31853
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.RectF com.appliedrec.verid.core.RecognizableFace.getBounds()' on a null object reference
        at com.appliedrec.ver_ididcapture.CardCaptureFragment$13.run(CardCaptureFragment.java:761)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6662)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
**Attached screenshot below:**

<img width="1398" alt="Screen Shot 2019-08-08 at 3 41 45 PM" src="https://user-images.githubusercontent.com/47731403/62692794-1f031d00-b9f3-11e9-907b-034012723a47.png">

**Sample card we test:**

![DL_Front-1](https://user-images.githubusercontent.com/47731403/62693016-7acda600-b9f3-11e9-8883-4e913421fbe0.jpg)

**Comment by jakubdolejs** [comment]
Hi @sanitul,
1. The face on the card doesn't get picked up by the face detector. At least when I run the detection off the screen. There is too much contrast between the back of the card and the photo.
2. As of c07e5410ea0a5444c49ab4601cda421716682111 the error is handled and the app won't crash. Instead, the user will see an alert indicating the reason for the failure.
